<?php
declare(strict_types=1);
/**
 * @var \Elogic\Weather\Block\Weather $block
 * @var Elogic\Weather\Api\Data\ElogicWeatherInterface $model
 */

$model = $block->getWeatherData();
if ($model->getEntityId()): ?>
<table>
    <tbody>
    <tr>
        <td colspan="2"><?= $model->getData('name');?></td>
    </tr>
    <tr>
        <td><?= $model->getData('additional/main/temp');?>&#176; C</td>
        <td><?= __('Feels like %1 &#176;C.', $model->getData('additional/main/feels_like')); ?>
            <?= $model->getData('additional/info/description');?></td>
    </tr>
    <tr>
        <td>
            <?= __('Wind %1 m/s N', $model->getData('additional/wind/speed')); ?>
        </td>
        <td>
            <?= __('Atmospheric pressure %1 Pa', $model->getData('additional/main/pressure')); ?>
        </td>
    </tr>
    <tr>
        <td colspan="2">
            <?= __('Humidity: %1 %', $model->getData('additional/main/humidity')); ?>
        </td>
    </tr>
    </tbody>
</table>
<?php endif;?>
