<?php
declare(strict_types=1);
/**
 * @var \Elogic\Weather\Block\Weather $block
 * @var Elogic\Weather\Api\Data\ElogicWeatherInterface $model
 */

$model = $block->getWeatherData();
if ($model != null): ?>
<table>
    <tbody>
    <tr>
        <td colspan="2"><?= $model->getData('name');?></td>
    </tr>
    <tr>
        <td><?= $model->getData('additional/main/temp');?>&#176; C</td>
        <td>Feels like <?= $model->getData('additional/main/feels_like');?>&#176;C.
            <?= $model->getData('additional/info/description');?></td>
    </tr>
    <tr>
        <td>
            Wind <?= $model->getData('additional/wind/speed');?>m/s N
        </td>
        <td>Atmospheric pressure <?= $model->getData('additional/main/pressure');?>Pa</td>
    </tr>
    <tr>
        <td colspan="2">Humidity:<?= $model->getData('additional/main/humidity');?>%</td>
    </tr>
    </tbody>
</table>
<?php endif;?>
