<?php
declare(strict_types=1);
/**
 * @var \Elogic\Weather\Block\Weather $block
 */

$info = $block->getWeatherData();
?>
<table>
    <tbody>
    <tr>
        <td colspan="2"><?= $info['name'];?></td>
    </tr>
    <tr>
        <td><?= $info['main']['temp'];?>&#176; C</td>
        <td>Feels like <?= $info['main']['feels_like'];?>&#176;C. <?= $info['info']['description'];?></td>
    </tr>
    <tr>
        <td>
            Wind <?= $info['wind']['speed'];?>m/s N
        </td>
        <td>Atmospheric pressure <?= $info['main']['pressure'];?>Pa</td>
    </tr>
    <tr>
        <td colspan="2">Humidity:<?= $info['main']['humidity'];?>%</td>
    </tr>
    </tbody>
</table>
