<?php
declare(strict_types=1);

namespace Elogic\Weather\Model;

use Elogic\Weather\Api\Data\ElogicWeatherExtensionInterface;
use Elogic\Weather\Api\Data\ElogicWeatherInterface;
use Magento\Framework\Api\AttributeValueFactory;
use Magento\Framework\Api\ExtensionAttributesFactory;
use Magento\Framework\Model\AbstractExtensibleModel;
use Magento\Framework\Serialize\Serializer\Json;

/**
 * Class ElogicWeather
 * @package Elogic\Weather\Model
 */
class ElogicWeather extends AbstractExtensibleModel implements ElogicWeatherInterface
{
    /**
     * @var Json
     */
    protected $json;

    public function __construct(
        Json $json,
        \Magento\Framework\Model\Context $context,
        \Magento\Framework\Registry $registry,
        ExtensionAttributesFactory $extensionFactory,
        AttributeValueFactory $customAttributeFactory,
        \Magento\Framework\Model\ResourceModel\AbstractResource $resource = null,
        \Magento\Framework\Data\Collection\AbstractDb $resourceCollection = null,
        array $data = []
    ) {
        $this->json = $json;
        parent::__construct($context, $registry, $extensionFactory, $customAttributeFactory, $resource, $resourceCollection, $data);
    }

    /**
     * @inheritDoc
     */
    protected function _construct()
    {
        $this->_init(ResourceModel\ElogicWeatherResource::class);
    }

    /**
     * @inheritDoc
     */
    public function getEntityId(): int
    {
        return (int)$this->getData(self::ENTITY_ID);
    }

    /**
     * @param int $entityId
     * @return void
     */
    public function setEntityId($entityId)
    {
        $this->setData(self::ENTITY_ID, $entityId);
    }

    /**
     * @inheritDoc
     */
    public function getInfo(): string
    {
        return $this->getData(self::INFO);
    }

    /**
     * @inheritDoc
     */
    public function setInfo(string $info): void
    {
        $this->setData(self::INFO, $info);
    }

    /**
     * @inheritDoc
     */
    public function getMain(): ?string
    {
        return $this->getData(self::MAIN);
    }

    /**
     * @inheritDoc
     */
    public function setMain(string $main): void
    {
        $this->setData(self::MAIN, $main);
    }

    /**
     * @inheritDoc
     */
    public function getWind(): ?string
    {
        return $this->getData(self::WIND);
    }

    /**
     * @inheritDoc
     */
    public function setWind(string $wind): void
    {
        $this->setData(self::WIND, $wind);
    }

    /**
     * @inheritDoc
     */
    public function getName(): ?string
    {
        return $this->getData(self::NAME);
    }

    /**
     * @inheritDoc
     */
    public function setName(string $name): void
    {
        $this->setData(self::NAME, $name);
    }

    /**
     * @inheritDoc
     */
    public function getInTown(): int
    {
        return (int)$this->getData(self::IN_TOWN);
    }

    /**
     * @return ElogicWeather
     */
    public function beforeSave(): ElogicWeather
    {
        $this->setInfo($this->json->serialize($this->getData('info')));
        $this->setMain($this->json->serialize($this->getData('main')));
        $this->setWind($this->json->serialize($this->getData('wind')));
        return parent::beforeSave(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function setInTown(int $inTown): void
    {
        $this->setData(self::IN_TOWN, $inTown);
    }

    /**
     * @inheritDoc
     */
    public function getCreatedAt(): string
    {
        return $this->getData(self::CREATED_AT);
    }

    /**
     * @inheritDoc
     */
    public function getExtensionAttributes()
    {
        return $this->_getExtensionAttributes();
    }

    /**
     * @inheritDoc
     */
    public function setExtensionAttributes(
        ElogicWeatherExtensionInterface $extensionAttributes
    ) {
        $this->_setExtensionAttributes($extensionAttributes);
    }
}
